pipeline {
    agent any
    stages {
        stage('Code Fetch') {
            steps {
                sh 'echo Fetching code from github'
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'github', url: 'https://github.com/anjalighadei/MyDemoWebSite.git']]])
            }
        }
        stage('Build') {
            steps {
                sh 'echo Building and creating war file'
            }
            
        }
        stage('Upload to Jfrog') {
            steps {
                sh 'echo Build artifact uploading to Jfrog'
            }
        }
    }
}
